settings:
  root_directory: C:\Music
  save_directory: C:\YAML
  track_identifier: track_number
  scan_mode: all
  modified_time_days: 7

# Tags to read from their respective file types.
# This includes both tags used for matching and 
# editing.
read_tags:
  .flac:
    - ALBUMARTIST
    - ALBUM
    - TITLE
    - TRACKNUMBER
    - DISPLAY ARTIST
    - ITUNESADVISORY
  .mp3:
    - TPE2
    - TALB
    - TIT2
    - TRCK
    - TXXX:DISPLAY ARTIST
    - TXXX:ITUNESADVISORY

# Tags used for matching files in plex.
# Each value must correspond to a tag
# in read_tags.
matching_tags:
  .flac:
    album_artist: ALBUMARTIST
    album_title: ALBUM
    track_title: TITLE
    track_number: TRACKNUMBER
  .mp3:
    album_artist: TPE2
    album_title: TALB
    track_title: TIT2
    track_number: TRCK

# Tags used for updating track fields in Plex.
# Currently only supports original_artist and
# title.
modification_tags:
  .flac:
    title: TITLE
    original_artist: DISPLAY ARTIST
  .mp3:
    title: TIT2
    original_artist: TXXX:DISPLAY ARTIST